research_task:
  description: >
    Conduct thorough research about {topic} from all the text files provided
  expected_output: >
    A comprehensive research document with well-organized sections covering
    all the relevant aspects of {topic}.
  agent: researcher_agent

search_manager_task:
  description: >
    Search the web for links related to {topic}. And then pass any relevant links to a scraping_manager.
    Search for a maximum of 5 links, and pick only up to 3 to pass to the scraping_manager
  expected_output: >
    A list of all the relevant links that need to be scraped.
  agent: search_manager

scraping_manager_task:
  description: >
    Scrape {website_url} for everything related to {topic}, and after the chunks are stored as separate files,
    pass on each to a researcher by giving them their respective filename. If the site cannot be scraped due
    to the token limit, skip the site. Create chunks of a size of 2000.
  expected_output: >
    A list of all the relevant filenames that need to be researched on.
  agent: scraping_manager

summary_task:
  description: >
    Analyze the aggregated research and create an unbiased and accurate summary about {topic}.
    If you aren't given any research, return nothing.
  expected_output: >
    A clear, concise, and impactful summary. Ensuring that no important detail
    is lost while removing unnecessary fluff.
  agent: summarizer_agent
  output_file: output/summary.md
